---
# tasks file for zookeeper

- name: Download and unpack zookeeper
  unarchive:
    remote_src: yes
    src: https://archive.apache.org/dist/zookeeper/zookeeper-3.4.13/zookeeper-3.4.13.tar.gz
    dest: '{{solr_install_dir}}/'

  tags:
    - zookeeper_unpack

- name: remove zoo_sample.config
  shell: rm -f '{{zoo_conf_dir}}/zoo_sample.cfg'


- name: copy zoo.cfg file to hosts
  copy:
    src: ./roles/zookeeper/files/zoo.cfg
    dest: '{{zoo_conf_dir}}/zoo.cfg'

- name: copy zoo.sh file to conf dir
  copy:
    src: ./roles/zookeeper/files/zookeeper-env.sh
    dest: '{{zoo_conf_dir}}/zookeeper-env.sh'

- name: create zookeeper data dir
  file:
    path: "/var/lib/zookeeper"
    state: directory
    mode: "777"
    recurse: yes
  become: yes
  become_user: root

- name: add zoo_id to "/var/lib/zookeeper"
  copy:
    content: "{{zoo_id}}"
    dest: /var/lib/zookeeper/myid

# systemd option not worth it right now
- name: stop zookeeper
  shell: "{{zoo_bin_dir}}/zkServer.sh stop"

- name: start ZooKeeper
  shell: "{{zoo_bin_dir}}/zkServer.sh start"
