---
# tasks file for elastic

- name: run elastic master nodes
  include_tasks:
    file: elastic_cmds.yml

  tags:
    - start
    - stop
    - restart
    - never


- name: elastic complaining about this
  shell: sysctl -w vm.max_map_count=262144
  become: yes
  become_user: root
  tags:
    - setup
    - never
    - sysctl


- name: check if es has been downloaded
  stat:
    path: "{{es_root_dir}}"
  register: espath
  tags:
    - setup
    - never

- name: Download and unpack elastic
  unarchive:
    remote_src: yes
    src: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-linux-x86_64.tar.gz
    dest: '{{user_root_dir}}'

  when: espath.stat.isdir is not defined
  tags:
    - setup
    - never


- name: do kibana things
  include_tasks: kibana.yml
  vars:
    nodename: "{{globalIP}}"
    nethost: "{{ansible_subnet}}"
    discoverynodes: "{{discovery_nodes}}"
  tags:
    - kibana_config


- name: do metricbeat things for kibana
  include_tasks: metricbeat.yml
  vars:
    nodename: "{{globalIP}}"
    nethost: "{{ansible_subnet}}"
    discoverynodes: "{{discovery_nodes}}"
  tags:
    - met
    - metric_config
    - never

- name: mk es log dir
  file:
    path: "{{es_log_dir}}"
    state: directory
    mode: "777"
    recurse: yes
  become: yes
  become_user: root
  tags:
    - setup
    - never

- name: mk es data dir
  file:
    path: "{{es_data_dir}}"
    state: directory
    mode: "777"
    recurse: yes
  become: yes
  become_user: root
  tags:
    - setup
    - never

- name: post data
  include_tasks:
    file: upload_data.yml
  tags:
    - upload
    - never


- name: pip elasticsearch
  include_tasks:
    file: install_py_dep.yml
  tags:
    - pipelastic
    - never
