---
# tasks file for elastic

- name: check if es has been downloaded
  stat:
    path: "{{es_root_dir}}"
  register: espath


- name: Download and unpack elastic
  unarchive:
    remote_src: yes
    src: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-linux-x86_64.tar.gz
    dest: '{{user_root_dir}}'

  when: espath.stat.isdir is not defined



- name: check if kibana has been downloaded
  stat:
    path: "{{kibana_root_dir}}"
  register: kpath


- name: Download and unpack kibana
  unarchive:
    remote_src: yes
    src: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.5.1-linux-x86_64.tar.gz
    dest: '{{user_root_dir}}'

  when: kpath.stat.isdir is not defined
