- hosts: localhost
  tasks:
    - name: open solr admin panel
      command: open http://"{{node0}}":8983
      async: 99999
      poll: 0
      tags:
        - solr_panel
    - name: view remote JMX monitoring for solr nodes
      command: jconsole "{{node0}}":18983 "{{node1}}":18983 "{{node2}}":18983 "{{node3}}":18983 "{{node7}}":18983 "{{node11}}":18983 "{{node4}}":18983 "{{node8}}":18983 "{{node12}}":18983 "{{node5}}":18983 "{{node9}}":18983 "{{node13}}":18983 "{{node6}}":18983 "{{node10}}":18983 "{{node14}}":18983
      async: 99999
      poll: 0
      tags:
        - jmx
  tags:
    - local

- hosts: generatorNode
  roles:
    - benchmark
  tags:
    - solrj
