---
# tasks file for cloud-env

# - name: Ensure ramdisk directory exists
#   file:
#     dest: "{{ ramdisk_path }}"
#     mode: '01777'
#     state: directory
#
# - name: Ensure ramdisk is mounted
#   mount:
#     name: "{{ ramdisk_path }}"
#     src: tmpfs
#     fstype: tmpfs
#     opts: "size={{ ramdisk_size }}"
#     state: mounted

- name: raise file and proc limits on servers
  blockinfile:
    path: '/etc/security/limits.conf'
    block: |
      {{ansible_user}}       soft    nproc           65000
      {{ansible_user}}       hard    nproc           65000
      {{ansible_user}}       soft    nofile          65000
      {{ansible_user}}       hard    nofile          65000
  become: yes
  become_user: root
  tags:
    - raise_limits

- name: update packages
  apt:
    update_cache: yes
  become: yes
  become_user: root

- name: ensure jdk8 is installed
  apt:
    name: openjdk-8-jdk
  become: yes
  become_user: root


- name: sudo apt-get install packages
  apt:
    name: "{{ packages }}"
    state: present
    update-cache: yes
  become: yes
  become_user: root
  tags:
    - install_packages

- name: download ptp
  git:
    repo: git://git.code.sf.net/p/linuxptp/code
    dest: ./linuxptp
    force: yes
  tags:
    - ptp


- name: install ptp
  make:
    chdir: '{{ptp_install_dir}}'
    target: install
  become: yes
  become_user: root
  tags:
    - ptp
