---
# tasks file for cloud-env

# - name: Ensure ramdisk directory exists
#   file:
#     dest: "{{ ramdisk_path }}"
#     mode: '01777'
#     state: directory
#
# - name: Ensure ramdisk is mounted
#   mount:
#     name: "{{ ramdisk_path }}"
#     src: tmpfs
#     fstype: tmpfs
#     opts: "size={{ ramdisk_size }}"
#     state: mounted

- name: ensure jdk8 is installed
  apt:
    name: openjdk-8-jdk
  become: yes
  become_user: root

- name: update packages
  apt:
    update_cache: yes
  become: yes
  become_user: root

- name: sudo apt-get install python3-pip, python3-dev
  apt:
    name: "{{ packages }}"
    state: present
    update-cache: yes
  become: yes
  become_user: root
