---
# defaults file for zookeeper

zoo_install_dir: /users/dporte7/
zoo_conf_dir: /users/dporte7/zookeeper-3.4.13/conf
zoo_root_dir: /users/dporte7/zookeeper-3.4.13
zoo_bin_dir: /users/dporte7/zookeeper-3.4.13/bin
