- name: include the vars
  include_vars: /Users/dporter/projects/solrcloud/playbooks/roles/upload_data/defaults/main.yml

- name: update Query Cache configs
  script: ../files/update_query_cache.sh "{{ansible_subnet}}" "{{collection_name}}"
  tags:
    - update_query

- name: update Doc Cache configs
  script: ../files/update_doc_cache.sh "{{ansible_subnet}}" "{{collection_name}}"
  tags:
    - update_doc
