---
# tasks file for upload_data
- name: include the vars
  include_vars: /Users/dporter/projects/solrcloud/playbooks/roles/upload_data/defaults/main.yml

- name: pull AWS index
  shell: aws s3 sync "s3://{{s3_bucket_name}}/{{ansible_subnet}}/{{collection_name}}" .
  ignore_errors: yes
  no_log: True

  args:
    chdir: '{{solr_home}}'
