# tasks file for upload_data
- name: Check if data has been downloaded already.
  stat:
    path: /users/dporte7/reviews_Electronics_5.json
  register: data_download_path_status

# unarchive module maintainers argued about .gz file support https://github.com/ansible/ansible-modules-core/issues/3241
# - name: Download data set
#   unarchive:
#     remote_src: yes
#     src: http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Electronics_5.json.gz
#     dest: '{{data_upload_dir}}'
#     creates: "{{data_upload_dir}}/reviews_rf2q_Electronics_5.json"
#     extra_opts: --gunzip
#
#   tags:
#     - download_data

- name: download data
  shell: wget http://snap.stanford.edu/data/amazon/productGraph/categoryFiles/reviews_Electronics_5.json.gz
  args:
    creates: /users/dporte7/reviews_Electronics_5.json.gz'
  when:
    - data_download_path_status.stat.exists == False

- name: unzip data
  shell: gunzip -f "{{data_upload_dir}}/reviews_Electronics_5.json.gz"
  args:
    creates: '{{data_upload_dir}}/reviews_Electronics_5.json'
  when:
    - data_download_path_status.stat.exists == False
