---


- name: check if aws has the index
# aws s3 ls s3://solr-8-dporter/10.10.1.12/reviews_rf32_s1_clustersize12
  shell: aws s3 ls "s3://{{s3_bucket_name}}/{{ansible_subnet}}/{{collection_name}}"
  register: index_result
  ignore_errors: yes


- name: include tasks when index is there
  include_tasks:
    file: 'tasks/aws_pull.yml'
    apply:
      tags:
        - aws_pull
  when: "'PRE' in index_result.stdout"


# COMPLETE after second playbook step




# - name: update solrconfig to use RAM index
#   script: ../files/update_solrconfig.sh "{{ansible_subnet}}" "{{collection_name}}"
#   when: "'Error 404 Not Found' in check_result.stdout"
#   tags:
#     - update_config
#     - exp_mode
