

# aws s3 rm s3://mybucket --recursive
- name: include the vars
  include_vars: "{{SAPA_HOME}}/playbooks/roles/upload_data/defaults/main.yml"

- name: delete AWS index "{{collection_name}}"
  shell: aws s3 rm "s3://tard
  ignore_errors: yes
  no_log: True
