---
# handlers file for solr
  - name: stop solr
    shell: ./solr/bin/solr stop -c
    register: solr_stop_result
    ignore_errors: True
    args:
      chdir: '{{solr_install_dir}}'
    environment:
      SOLR_HOST: "{{ansible_subnet}}"
      GLOBALIP: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"

    failed_when:
      - solr_stop_result.rc != 0
      - '"No process found" not in solr_stop_result'
    listen:
      - "stop solr services"

# q has been added to issue WARN log level only -> didnt seem to make a big difference
  - name: start solr
    shell: ./solr/bin/solr start -q -c -Dcom.sun.management.jmxremote
    args:
      chdir: '{{solr_install_dir}}'
    environment:
      SOLR_HOST: "{{ansible_subnet}}"
      GLOBALIP: "{{hostvars[inventory_hostname]['ansible_default_ipv4']['address']}}"

    listen:
      - "start solr services"
