---
# tasks file for benchmark
# - name: run dstat on each machine
#   shell: "(dstat --time --output '{{ansible_subnet}}'_dstat_'{{pyscript}}'.csv &>/dev/null &)"
#   async: 20
#   poll: 0

# - name: stop dstat
#   shell: "ps aux | grep -i 'dstat*' | awk -F' ' '{print $2}' | xargs kill -9"

- name: copy solrj source to load nodes
  copy:
    src: /Users/dporter/projects/solrcloud/solrclientserver
    dest: "/users/{{ansible_user}}/"
    owner: '{{ansible_user}}'
  tags:
    - copy_solrj

- name: Running mvn clean install
  shell: "mvn clean install"
  args:
    chdir: '{{pom_path}}'
  register: mvn_result
  tags:
    - mvn_install

# - name: Running solrj
#   shell: java -cp target/solrclientserver-1.0-SNAPSHOT.jar '{{main_class}}'
#   async: 9999
#   poll: 0
#   args:
#     chdir: '{{pom_path}}'
#   tags:
#     - run_solrj

# cd solrclientserver;java -cp target/solrclientserver-1.0-SNAPSHOT.jar com.dporte7.solrclientserver.DistributedWebServer
