- name: include the vars
  include_vars: "{{SAPA_HOME}}/playbooks/sapa_vars.yml"

- name: update Query Cache configs
  script: ../files/update_query_cache.sh "{{ansible_subnet}}" "{{collection_name}}"
  tags:
    - update_query

- name: update Doc Cache configs
  script: ../files/update_doc_cache.sh "{{ansible_subnet}}" "{{collection_name}}"
  tags:
    - update_doc
