---
# defaults file for elastic
user_root_dir: /users/dporte7
es_root_dir: /users/dporte7/elasticsearch-7.5.1
kibana_root_dir: /users/dporte7/kibana
es_data_dir: /var/elasticsearch/data
es_log_dir: /var/elasticsearch/log
cache_percentage: "50%"
metric_root_dir: /users/dporte7/metricbeat
