#get the 8_1 version of solr (this repo was forked from apache on 6/12/19).


- name: Check if Solr has been installed already.
  stat:
    path: "{{ solr_install_dir }}"
  register: solr_install_path_status

- name: 'Download Solr to -> "{{solr_install_dir}}"'
  git:
      repo: https://github.com/DavidCPorter/lucene-solr.git
      dest: "{{solr_install_dir}}"
      version: "{{git_branch_name}}"
      force: yes
  register: solr_git_status
  when: solr_install_path_status.stat.exists == False
  tags:
    - solr_update


- name: Run ant-ivy.
  shell: ant ivy-bootstrap
  args:
    chdir: "{{solr_install_dir}}"
  when: solr_install_path_status.stat.exists == False

- name: Build solr with ant.
  shell: ant compile
  args:
    chdir: '{{solr_install_dir}}'
  when: solr_install_path_status.stat.exists == False

- name: run ant server
  shell: ant server
  args:
    chdir: '{{solr_install_dir}}/solr'
  when: solr_install_path_status.stat.exists == False

- name: remove old solr.in.sh
  shell: rm -f '{{solr_install_dir}}/solr/bin/solr.in.sh'
  tags:
    - solrinsh

# not the best convention here...
- name: copy solr init file to hosts
  copy:
    src: ./roles/solr/files/solr.in.sh
    dest: '{{solr_install_dir}}/solr/bin'
  tags:
    - config
    - solrinsh





- name: create and grant log dir permissions for solr
  file:
    path: "{{solr_log_dir}}"
    state: directory
    mode: "777"
    recurse: yes
  become: yes
  become_user: root

- name: add slow query logging for queries > .5s to default solrconfig.xml
  lineinfile:
    path: '{{solr_install_dir}}/solr/server/solr/configsets/_default/conf/solrconfig.xml'
    insertbefore: '</query>'
    line: '<slowQueryThresholdMillis>500</slowQueryThresholdMillis>'
  tags:
    - slow_query
#  decided to completely disable logging for experiments.
- name: add slow query logging for queries > .5s to default solrconfig.xml
  lineinfile:
    path: '{{solr_install_dir}}/solr/server/solr/configsets/_default/conf/solrconfig.xml'
    state: absent
    regex: '<slowQueryThresholdMillis>500</slowQueryThresholdMillis>'
  tags:
    - remove_slow_query

- name: modify solr executable ~/solr-8_0/solr/bin/solr
  lineinfile:
    path: '{{solr_install_dir}}/solr/bin/solr'
    regex: '^REMOTE_JMX_OPTS+=("-Djava.rmi.server.hostname=$SOLR_HOST")'
    line: 'REMOTE_JMX_OPTS+=("-Djava.rmi.server.hostname={{globalIP}}")'
  tags:
    - rmi




- name: calling handler for stopping solr
  command: echo "stopping solr..."
  notify:
    - "stop solr services"
  tags:
    - solr_restart
    - solr_stop

- name: calling handler for starting solr
  command: echo "starting solr..."
  notify:
    - "start solr services"
  tags:
    - solr_restart
    - solr_start
