# playbook


- hosts: singleNode
  tasks:
  - name: set singleNode chroot for znodes for all solr node configs
    shell: bash "{{solr_bin_exec}}" zk mkroot /singleNode
    ignore_errors: yes

  - name: set twoNode chroot for znodes for all solr node configs
    shell: bash "{{solr_bin_exec}}" zk mkroot /twoNode
    ignore_errors: yes

  - name: set fourNode chroot for znodes for all solr node configs
    shell: bash "{{solr_bin_exec}}" zk mkroot /fourNode
    ignore_errors: yes

  - name: set eightNode chroot for znodes for all solr node configs
    shell: bash "{{solr_bin_exec}}" zk mkroot /eightNode
    ignore_errors: yes


  - name: set sixteenNode chroot for znodes for all solr node configs
    shell: bash "{{solr_bin_exec}}" zk mkroot /sixteenNode
    ignore_errors: yes

  - name: set twentyfourNode chroot for znodes for all solr node configs
    shell: bash "{{solr_bin_exec}}" zk mkroot /twentyfourNode
    ignore_errors: yes

  - name: set default chroot for znodes for all solr node configs
    shell: bash "{{solr_bin_exec}}" zk mkroot /default
    ignore_errors: yes
