
- hosts: twoNode
  tasks:
    - name: delete solr data
      file:
        path: /var/solr
        state: absent
      become: yes
      become_user: root

    - name: delete solr home dir
      file:
        path: "{{solr_install_dir}}"
        state: absent
