- hosts: generatorNode
  tasks:
  - name: copy traffic_gen to loads
    copy:
      src: "{{scripts_path}}"
      dest: "{{home}}"
  - name: copy terms to loads
    copy:
      src: "{{terms_path}}"
      dest: "{{home}}"
      mode: '0777'
