# playbook for cloudconfig
- hosts: allNodes
  roles:
    - cloud-env
  tags:
    - never
    - general

- hosts: generatorNode
  tasks:
  - name: pip install numpy
    pip:
      name: numpy
      executable: /usr/bin/pip3
  tags:
    - never
    - pip_installs

- hosts: generatorNode
  tasks:
    - name: pip install elasticsearch
      pip:
        name: elasticsearch
        executable: /usr/bin/pip3
  tags:
    - never
    - pip_installs

- hosts: mylocal
  tasks:
    - name: generate utils.sh to benchmarkscripts/utils/utils.sh
      template:
        src: roles/cloud-env/templates/utils.sh
        dest: "{{SAPA_HOME}}/benchmark_scripts/utils/utils.sh"
  tags:
    - utils
    - never
