# playbook

#- hosts: masterNodes
#  gather_facts: no
#  tasks:
#    set_facts:
#      discovery_nodes: "{{discovery_ ansible_subnet] }}"
#  tags:
#    - start

- hosts: masterNodes
  roles:
    - elastic
  vars:
    cache_percentage_of_heap: "{{cache_percentage}}"
    cluster_name: twoNode
  tags:
    - main

- hosts: singleGenerator
  tasks:
    - name: include tasks download_json
      include_tasks:
        file: roles/elastic/tasks/download_json.yml
  tags:
    - load_json
    - never

- hosts: singleGenerator
  tasks:
    - name: truncate the json
      shell: head -n 100000 reviews_Electronics_5.json > reviews.json
  tags:
    - docker
    - never

- hosts: singleGenerator
  tasks:
    - debug:
        var: groups['singleNode']
  tags:
    - woah

- hosts: singleGenerator
  tasks:
    - name: include vars for elastic indexing ansible script
      include_vars: "{{SAPA_HOME}}/playbooks/sapa_vars.yml"

    - name: include tasks run indexing
      include_tasks:
        file: roles/elastic/tasks/do_index.yml
        apply:
          vars:
            hostname: "{{node0_subnet}}"
            hard_replicas: "{{ replicas|int - shards|int }}"

  tags:
    - run_script
    - never


  # tags:
    # - start_masternodes
    # - never

# - hosts: thirdMaster
#   roles:
#     - elastic
#   vars:
#     master_flag: true
#     data_flag: false
#     discovery_nodes:
#       - "{{node0}}"
#       - "{{node1}}"
#     cluster_name: twoNode
