# playbook for cloudconfig

- hosts: twoNode
  roles:
    - upload_data
  tags:
    - never
    - begin_exp

- hosts: singleNode
  tasks:
    - name: this task will run when aws_index is false
      include_tasks: roles/upload_data/tasks/aws_absent.yml
  tags:
    - never
    - begin_exp

# need to put begin_exp tag here to enable tracing.
- hosts: twoNode
  tasks:
    - name: update solr.xml
      copy:
        src: "{{upload_data_file_path}}/solr.xml"
        dest: "{{solr_home}}"
        force: yes
  tags:
    - begin_exp
#

- hosts: twoNode
  tasks:
    - name: run this at the end of each experiment AKA aws_exp_reset
      include_tasks:
        file: roles/upload_data/tasks/aws_reset.yml
  tags:
    - never
    - aws_exp_reset

- hosts: singleNode
  tasks:
    - name: update collection configs
      include_tasks:
        file: roles/upload_data/tasks/all_config.yml
  tags:
    - never
    - update_collection_configs
