# playbook

- hosts: singleNode
  tags:
    - znode
    - setup
  tasks:
  - name: set singleNode chroot for znodes for all solr node configs
    shell: bash "{{solr_bin_exec}}" zk mkroot /singleNode
    ignore_errors: yes

  - name: set twoNode chroot for znodes for all solr node configs
    shell: bash "{{solr_bin_exec}}" zk mkroot /twoNode
    ignore_errors: yes

  - name: set fourNode chroot for znodes for all solr node configs
    shell: bash "{{solr_bin_exec}}" zk mkroot /fourNode
    ignore_errors: yes

  - name: set eightNode chroot for znodes for all solr node configs
    shell: bash "{{solr_bin_exec}}" zk mkroot /eightNode
    ignore_errors: yes


  - name: set sixteenNode chroot for znodes for all solr node configs
    shell: bash "{{solr_bin_exec}}" zk mkroot /sixteenNode
    ignore_errors: yes

  - name: set twentyfourNode chroot for znodes for all solr node configs
    shell: bash "{{solr_bin_exec}}" zk mkroot /twentyfourNode
    ignore_errors: yes

  - name: set default chroot for znodes for all solr node configs
    shell: bash "{{solr_bin_exec}}" zk mkroot /default
    ignore_errors: yes

- hosts: solrNodes
  roles:
    - solr
  vars:
    chroot: default
  tags:
    - never
    - setup


- hosts: solrNodes
  tasks:
    - name: delete solr data
      file:
        path: /var/solr
        state: absent
      become: yes
      become_user: root
      tags:
        - never
        - burn_solr

    - name: delete solr home dir
      file:
        path: "{{prev_solr_install_dir}}"
        state: absent
      tags:
        - never
        - burn_solr
