---
# handlers file for solr
  - name: stop solr
    shell: ./solr/bin/solr stop -c -all
    register: solr_stop_result
    ignore_errors: yes
    args:
      chdir: '{{solr_install_dir}}'

    listen:
      - "stop solr services"

  - name: fail the play if the previous command did not succeed
    fail:
      msg: "the command failed"
    when:
      - solr_stop_result.rc != 0
      - '"No process found" not in solr_stop_result.stdout'
    listen:
      - "stop solr services"

# q has been added to issue WARN log level only -> didnt seem to make a big difference
  - name: start solr
    shell: ./solr/bin/solr start -c -q -z "{{node0}}:2181,{{node1}}:2181,{{node2}}:2181/{{chroot}}"
    register: solr_start_result
    ignore_errors: yes

    args:
      chdir: '{{solr_install_dir}}'
    listen:
      - "start solr services"

  - name: fail the start solr if conditions not met
    fail:
      msg: "the command failed"
    when:
      - solr_start_result.rc != 0
      - "'Port 8983 is already being used by another process' not in solr_start_result.stdout"

    listen:
      - "start solr services"
